extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_Ground_layer1_area1_lights;
extern u8 ccm_dl_BinarySmallStones_i8[];
extern Vtx ccm_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cylinder_mesh_layer_1_vtx_0[96];
extern Gfx ccm_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Platform_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Platform_mesh_layer_1_vtx_0[57];
extern Gfx ccm_dl_Platform_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_FlatM[];
extern Gfx mat_revert_ccm_dl_FlatM[];
extern Gfx mat_ccm_dl_Ground_layer1_area1[];
extern Gfx mat_revert_ccm_dl_Ground_layer1_area1[];
extern Gfx ccm_dl_Cylinder_mesh_layer_1[];
extern Gfx ccm_dl_Platform_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
