extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_f3dlite_material_layer1_area1_lights;
extern u8 ccm_dl_Unseen_Forest_Purple_Grass_ci8[];
extern u8 ccm_dl_Unseen_Forest_Purple_Grass_ci8_pal_rgba16[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[57];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_f3dlite_material_layer1_area1[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_layer1_area1[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
